### ISSUE TITLE
sdmx-json REST format Accept header in the cheat sheet

### ISSUE THREAD

**Issue by wc-lei** [sdmx-twg/sdmx-rest#108]
I am not sure if the cheat sheet needs to be updated, or the implementation of Eurostat's NSIWS needs to be adjusted. When I use the json format header from the cheat sheet in my data query against NSIWS, I always get an error saying it's invalid. The format that works is as follows:

- application/vnd.sdmx.data+json;version=1.0.0-wd

- application/vnd.sdmx.data+json;version=1.0

**Comment by sosna** [comment]
Thanks @wc-lei, for informing us. The media type specified in the cheat sheet is in line with the [SDMX-REST specification](https://github.com/sdmx-twg/sdmx-rest/blob/master/v2_1/ws/rest/docs/4_6_conneg.md), i.e. there is no typo.

I cannot comment on Eurostat's implementation, as I don't know it, but maybe it's good to contact them, so that they know about the issue.

The first media type you mentioned was used in the past for the **w**orking **d**raft version of SDMX-JSON (hence the `-wd` qualifier). Therefore, it's still valid, provided it returns the working draft version of SDMX-JSON and not the final 1.0.0 version (there were a few differences between the two).

The last one (with 1.0) is wrong, as it was decided to adopt [semantic versioning](https://semver.org/) for the new technical specs of SDMX (e.g. SDMX-JSON 1.0.0, SDMX-REST 1.4.0, etc.), and so the last digit is missing.

I hope this clarifies.

I will close this issue as it's not an issue with the SDMX-REST specification.

**Comment by dosse** [comment]
@sosna The current version of SDMX-JSON is indeed set to the full semantic version number "1.0.0". But it seems to me that fixing the **referencing** header to "application/vnd.sdmx.data+json;version=1.0.0" is not conform to semantic versioning. The quite strict semantic versioning scheme makes only sense if it is coupled with **wildcardable referencing**. It will be practicable impossible to change implementations with each SDMX-JSON patch version increase. Therefore referencing:  
- "application/vnd.sdmx.data+json;version=1.0" to get the last available patch version of the SDMX-JSON format within the minor version "1.0", 
- "application/vnd.sdmx.data+json;version=1" to get the last available minor version of the SDMX-JSON format within the major version "1", as well as
- "application/vnd.sdmx.data+json" to get the last available version of the SDMX-JSON format,  

should all be allowed and perfectly understood by the Rest server. Maybe this needs to be clarified in the documentation?
