### ISSUE TITLE
Allow querying for past data (previous "vintages")

### ISSUE THREAD

**Issue by dosse** [sdmx-twg/sdmx-rest#157]
SDMX rest should provide a way to retrieve the data (and only that) as it would have been retrieved at a specific point in time in the past, like a snapshot.

In SDMX-RI NSI web service, the following rest feature was already successfully implemented:
- A URL parameter `asOf=[date-time-and-zone]` can be used to specify a point in time in the past, with a value type similar to the `updatedAfter` parameter (allowing to specify a date-time with a time zone).
- The response is one dataset, which has the `validFrom` and `validTo` properties set to the `asOf` input value.
- The response `action` property is set to `information`, despite its deprecation earlier this year.

**Comment by sosna** [comment]
This feature might be interesting for other types or resources as well (e.g. structures or schemas). So, you could retrieve all information about a dataflow (dataflow, DSD, codelists, etc.), as it was at a certain point in time.

**Comment by sosna** [comment]
If asOf is set, then updatedAfter MUST be older than asOf. An updatedAfter more recent than asOf should return a validation error (422) or a “no match” error (404).

Let’s imagine the following:
asOf = 2024-07-10T14:42:00Z
updatedAfter = 2024-07-09T14:42:00Z

This would mean: Give me the data as they were in the database at my asOf time (2024-07-10T14:42:00Z), but only those that have been updated during the 24 hours before that (i.e. my updatedAfter).

**Comment by sosna** [comment]
Closed with PR #219

**Comment by dosse** [comment]
@sosna Concerning

> In case both `updatedAfter` and `asOf` are set, the service is expected to return a validation error if `updatedAfter` is more recent than `asOf`.

the behaviour should be consistent with the behaviour when only `updatedAfter` is used and its datetime is set to later than the current datetime (of the web server), which is currently not specified. If in this case 404 is returned by an implementation then also 404 should be returned when `updatedAfter` is later than `asOf`.

**Comment by sosna** [comment]
Thanks, @dosse. At what I think was your request (a loooong time ago 😂), we agreed to start using code 422 to distinguish between a query that is syntactically incorrect (code 400), and a query that is semantically incorrect (code 422). 

This case of having `updatedAfter` older than `asOf` is a clear case of a query that might be syntactically correct (2 timestamps are passed) but non-sensical. Therefore, I believe code 422 is reasonable and more explicit than a 404. After all, it's not that there are no data (at the moment). It is that there are no data, and there can't ever be any data... So, as API default, I'd argue this is better? What do you think?

**Comment by dosse** [comment]
I still believe that the behaviour in both cases should be consistent because the goal of the `asOf` query is to get the **same result** as the user would have received (or actually received) when he made the query at the `asOf` point in time in the past. If in the past, the user has received XXX then the same result should be returned later with `asOf`. The question thus is what should be the expected result when the `updatedAfter` timestamp is after the current datetime, which is currently left to the implementer. 404 seems to me more appropriate because no results correspond to the selection. 

Furthermore,, the `updatedAfter` being more recent than `asOf` represents a similar contradiction than a query with a filter `FREQ=M+A`, which also returns 404, I believe. There is probably a right balance to be found between what extend of validations we impose on implementations and how much "user-friendly" responses need to be.

**Comment by sosna** [comment]
A couple of comments:

- The meaning of `FREQ=M+A` depends on what FREQ is. If it is an attribute that supports multiple values, then this syntax is correct and, if nothing matches both M and A, then, yes, a `404` should be returned. If however FREQ is a dimension, then this query is non-sensical (you cannot have data where the dimension value is both M and A at the same time) and I would expect a `422` instead. To me, it is useful to distinguish between a query that can never return anything because it is wrong, and a query that is OK but for which we have no data at the moment (but maybe we'll have later).

- In this particular case, the query would mean: "Give me the data as we published them on the 6th of June 2020, but please, only what was updated in our systems after the 1st of January 2024". This can never return any result. It's just wrong. It could be wrong because I misunderstood what these parameters do. Or it could be wrong because I have a bug in my code, and what I meant to ask for was "Give me the data as we published them on the 1st of January 2024, but please, only what was updated in our systems after the 6th of June 2020". Whether I'm ignorant (the first reason) or I wrote buggy code (the second one), I know I will be grateful if the service tells me that there is something wrong with my query. Instead, if all I get is this generic "Sorry, we don't have any data matching your query", it is making it much more difficult for me to realize that there is a problem.

This being said, I will send another PR inviting to return a client error instead of a validation error.

**Comment by sosna** [comment]
Implemented in PR #220

**Comment by sosna** [comment]
@dosse: Yes, I agree with you, we should probably not start listing all specific details of what non-sensical means, as the list would most likely never be exhaustive 😊
