### ISSUE TITLE
Clarification Needed for Component Filter Comparison Operator of Time Periods

### ISSUE THREAD

**Issue by JBeHMS** [sdmx-twg/sdmx-rest#237]
There is some ambiguity/room for interpretation when it comes to the behaviour of the component filter comparison operator for time periods. Consider the following example: We query for the parameter `c[TIME_PERIOD]=lt:2020-02` and have a dataset containing an observation with `TIME_PERIOD="2020-Q1"`. Would this observation be returned or not?

**Comment by dosse** [comment]
The answer to this question was written explicitly in the previous SDMX-REST version 1.5 (and below): "_When comparing reporting weeks and days to higher order periods (e.g. quarters) one must account for **the actual time frames covered** by the periods to determine whether the data should be included._" This is still valid in SDMX-REST 2.X.

Because `c[TIME_PERIOD]=lt:2020-02` does not include the full time frame covered by `TIME_PERIOD="2020-Q1"`, the latter is not to be returned. To retrieve `TIME_PERIOD="2020-Q1"`, the query could contain `c[TIME_PERIOD]=lt:2020-04`.

**Comment by JBeHMS** [comment]
Thank you very much for the swift and thorough reply, @dosse!
