### ISSUE TITLE
Consider replacing 'http://a-sdw-wsrest.ecb.int' in docs with 'https://sdw-wsrest.ecb.europa.eu'

### ISSUE THREAD

**Issue by Analect** [sdmx-twg/sdmx-rest#26]
The examples at https://sdw-wsrest.ecb.europa.eu/ use this updated endpoint.
I know the a-sdw-wsrest.ecb.int end-point was intended as a test one.
However, as per the end of this thread: https://github.com/amattioc/SDMX/issues/30
... it can lead to some confusion, as the test end-point has some bogus data to illustrate the updatedAfter and includeHistory parametres.

**Comment by sosna** [comment]
Note: The issue affects 3 Wiki pages and not the normative specification or the cheat sheet.

**Comment by sosna** [comment]
@Analect thanks a lot for the proposed improvement.

As the intention of the tutorial is to let interested people discover and learn more about the API, we consider that using the test version of the web services provided by the ECB is more appropriate than using the production one.

However, in order to avoid confusion as you mentioned, we have added a short note below all sections containing examples, that indicates:
- That the test instance used in the examples is not suitable for production use;
- Where the production instance of the ECB web services can be found.

**Comment by Analect** [comment]
@sosna 
No problem. Thanks for making those changes.

This thread might not be the appropriate place:
Notwithstanding that, in my own 'path' to learning about this stuff, I had been trying to test the updatedAfter and includeHistory features on a 'live' (non-test) REST end-point. It was only by e-mailing the ECB statistics group that I was able to ascertain that, in their case, these are only supported on their 'RTD' dataflow.  Perhaps, as a suggestion, it would be great to have a wiki page on your repo that maybe contained this sort of info so others could benefit. 

Perhaps from your vantage point, you're in a better position to get that sort of information from individuals within the various agencies handling the SDMX-related projects.  Failing that, I suppose I could email each in turn and try to assemble a compendium of some sort.

Let me know your thoughts.

**Comment by sosna** [comment]
@Analect Yes, this sounds nice, thanks, and I have created an issue to capture this: https://github.com/sdmx-twg/sdmx-rest/issues/27
