### ISSUE TITLE
latest observation...

### ISSUE THREAD

**Issue by kalessine** [sdmx-twg/sdmx-rest#30]
Hi!
I have written some sdmx visualisation software to put SDMX data on a map, and one of the things I do is instead of using a drop down menu to select the time, I walk the tree of the data set, and pick out the latest time value, it seems a shame that i have to specify a time period range (for example 2008-2014) and then for each full key, I take only the latest observation for that country and display that on the map... and then discard the rest of the observations...
its not important that I get the latest observation for each full key, I just thought that it would be more efficient to be able to query for the latest observation rather than discarding the previous observations....
this is a minor issue =D
Cheers
  JG

**Comment by sosna** [comment]
Hi,

The API offers a parameter called `lastNObservations`, to which you can pass an integer. For example, to get the most recent value foroverall inflation of the EU countries: 

```
https://sdw-wsrest.ecb.europa.eu/service/data/ICP/M..N.000000.4.ANR?lastNObservations=1
```

However, there is no guarantee that the values returned will all be for the same period (for example, the last value for country X might be for, say, September 2015, while the last value for country Y might be for August 2015).

If the above is not acceptable, you will most likely need to use both the `endPeriod` and `lastNObservations` parameters.

Let us know if the above is OK so that we can close the ticket. Thanks!

**Comment by kalessine** [comment]
the problem there is that there is no way of knowing how many observations there are nor what order they are in when specifying lastNObservations i dont think i've ever seen anything in the specs either about what sorting order observations or series should be in.. (whether each dimension alphabetically(stably) sorted in descending order, starting with last dimension, ending with the first dimension) or with the latest updated data point first.
i am happy to close this as not being very important, the latest observation can be obtained client-side easily enough.. this was just my being annoyed at having to discard so many observations just to get the latest value for every country...
Thanks
   JG

**Comment by sosna** [comment]
OK, thanks.

Yes, you are right, the API does not offer an option to get the count of matching series and/or observations. Of course, implementers can already support that, either via SDMX attributes or annotations, but I'm not aware of any impementer that does that.

Regarding the order of observations however, I don't think it is an issue when using lastNObservations, as the spec states: "Integer specifying the maximum number of observations to be returned for each of the matching series, counting back from the most recent observation".
