### ISSUE TITLE
Review options for detail parameter

### ISSUE THREAD

**Issue by dosse** [sdmx-twg/sdmx-rest#48]
Review the information returned with **detail** parameter (full, stubs, ) for both Soap and Rest which are today different (full, stubs, completestubs, referencestubs, allstubs). There is a general need to return more information with stubs than currently specified (e.g. isFinal, structureURL, urn, isExternalReference and some times also annotations (with CategoryScheme_node_order)). A mean to get descriptions, isFinal and annotations in Rest without the Items of the ItemScheme is needed.

**Comment by sosna** [comment]
The SDMX-SOAP API currently offers a `CompleteStub` option. Adding this to the RESTful API would provide *description* and *annotations*, in addition to the already existing *identification information* and *name*. It could also cover *isFinal*, although this would mean diverging from the SOAP spec. I don't see this as an issue, as the RESTful API and the SOAP API, although similar, exhibit some differences (mainly because of their different target audience). @dosse, would that work for you?

**Comment by dosse** [comment]
That would be great. Could also the other options `referencestubs` and `allstubs` be added to the RESTful API?

**Comment by sosna** [comment]
The *current* version of the API already supports the following values: `allstubs`, `referencestubs` and `full`.

The *next* version of the API should add support for `completestubs`. This would provide *description*, *annotations* and *isFinal* information, in addition to the already existing identification information and name.

If this works for you, I'm happy to make the changes in the *develop* branch.

**Comment by sosna** [comment]
Addressed in the upcoming v1.3.0 release
